name: Publish to PyPi

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publishing
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.PUSH_TOKEN }}
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
