name: Pytest

on:
  push:
    paths-ignore:
      - 'VERSION'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r simbind/architect/requirements.txt pytest pytest-mock pytest-asyncio
    - name: Run tests
      run: pytest